name: Run JUnit Tests (Gradle)
on: [push]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew clean test
